### ISSUE TITLE
DeepBGC failed with KeyError: pfam_id

### ISSUE THREAD

**Issue by artur-matysik** [Merck/deepbgc#47]
Hi, 

I sometimes get an error: 

```
INFO    05/03 10:31:02   Loading model from: /home/art/.local/share/deepbgc/data/0.1.0/classifier/product_activity.pkl
INFO    05/03 10:31:02   Processing input file 1/1: NZ_PZDX01000459.gbk
INFO    05/03 10:31:02   ================================================================================
INFO    05/03 10:31:02   Processing record #1: NZ_PZDX01000459
INFO    05/03 10:31:02   Sequence already contains 2 CDS features, skipping CDS detection
INFO    05/03 10:31:02   Reusing already existing HMMER hmmscan result: NZ_PZDX01000459/tmp/NZ_PZDX01000459.pfam.domtbl.txt
INFO    05/03 10:31:02   Added 1 Pfam domains (1 unique PFAM_IDs)
INFO    05/03 10:31:02   Detecting BGCs using deepbgc model in NZ_PZDX01000459
INFO    05/03 10:31:02   Detected 1 BGCs using deepbgc model in NZ_PZDX01000459
INFO    05/03 10:31:02   Classifying 1 BGCs using product_class model in NZ_PZDX01000459
ERROR   05/03 10:31:02   pfam_id
Traceback (most recent call last):
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'pfam_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/main.py", line 113, in main
    run(argv)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/main.py", line 102, in run
    args.func.run(**args_dict)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/command/pipeline.py", line 177, in run
    step.run(record)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/pipeline/classifier.py", line 41, in run
    class_scores = self.model.predict(cluster_pfam_sequences)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/models/wrapper.py", line 119, in predict
    X_list = self.transformer.transform(samples)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 29, in transform
    X_list = [self._transform_sequence(sequence) for sequence in samples]
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 29, in <listcomp>
    X_list = [self._transform_sequence(sequence) for sequence in samples]
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 38, in _transform_sequence
    return pd.concat([t.transform(sequence) for t in self.transformers], sort=False)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 38, in <listcomp>
    return pd.concat([t.transform(sequence) for t in self.transformers], sort=False)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 204, in transform
    values = pd.get_dummies(X[self.column]).reindex(columns=self.unique_values, fill_value=0)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'pfam_id'
ERROR   05/03 10:31:02   ================================================================================
ERROR   05/03 10:31:02   DeepBGC failed with KeyError: pfam_id
ERROR   05/03 10:31:02   ================================================================================
```
What is the problem here?
Attached is the extracted contig that is throwing this error. 

[NZ_PZDX01000459.zip](https://github.com/Merck/deepbgc/files/6087821/NZ_PZDX01000459.zip)

Thanks!

**Comment by prihoda** [comment]
Hi @artur-matysik, thanks for reporting this. It was caused by CDS features whose "translation" field extended their boundaries. I fixed the issue, you can `pip install deepbgc==0.1.24`. The bioconda release should be ready within a day or so. 

Please confirm if this works, so that we can close this issue.

**Comment by artur-matysik** [comment]
Hi @prihoda, 

I updated deepbgc to 0.1.24 as instructed, but I still get same error (on the example file). Did I miss something?
Thanks!
Art. 

```
 _____                  ____    ____   ____ 
 |  _ \  ___  ___ ____ | __ )  / ___) / ___)
 | | \ \/ _ \/ _ \  _ \|  _ \ | |  _ | |    
 | |_/ /  __/  __/ |_) | |_) || |_| || |___ 
 |____/ \___|\___| ___/|____/  \____| \____)
=================|_|===== version 0.1.24 =====
INFO    05/03 16:08:52   Loading model from: /home/art/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl
Using TensorFlow backend.
WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:203: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING 05/03 16:08:54   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING 05/03 16:08:55   From /home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

INFO    05/03 16:08:55   Loading model from: /home/art/.local/share/deepbgc/data/0.1.0/classifier/product_class.pkl
/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
INFO    05/03 16:08:55   Loading model from: /home/art/.local/share/deepbgc/data/0.1.0/classifier/product_activity.pkl
INFO    05/03 16:08:55   Processing input file 1/1: NZ_PZDX01000459.gbk
INFO    05/03 16:08:55   ================================================================================
INFO    05/03 16:08:55   Processing record #1: NZ_PZDX01000459
INFO    05/03 16:08:55   Sequence already contains 2 CDS features, skipping CDS detection
INFO    05/03 16:08:55   Reusing already existing HMMER hmmscan result: NZ_PZDX01000459/tmp/NZ_PZDX01000459.pfam.domtbl.txt
INFO    05/03 16:08:55   Added 1 Pfam domains (1 unique PFAM_IDs)
INFO    05/03 16:08:55   Detecting BGCs using deepbgc model in NZ_PZDX01000459
INFO    05/03 16:08:55   Detected 1 BGCs using deepbgc model in NZ_PZDX01000459
INFO    05/03 16:08:55   Classifying 1 BGCs using product_class model in NZ_PZDX01000459
ERROR   05/03 16:08:55   pfam_id
Traceback (most recent call last):
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'pfam_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/main.py", line 113, in main
    run(argv)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/main.py", line 102, in run
    args.func.run(**args_dict)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/command/pipeline.py", line 177, in run
    step.run(record)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/pipeline/classifier.py", line 41, in run
    class_scores = self.model.predict(cluster_pfam_sequences)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/models/wrapper.py", line 119, in predict
    X_list = self.transformer.transform(samples)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 29, in transform
    X_list = [self._transform_sequence(sequence) for sequence in samples]
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 29, in <listcomp>
    X_list = [self._transform_sequence(sequence) for sequence in samples]
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 38, in _transform_sequence
    return pd.concat([t.transform(sequence) for t in self.transformers], sort=False)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 38, in <listcomp>
    return pd.concat([t.transform(sequence) for t in self.transformers], sort=False)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/features.py", line 204, in transform
    values = pd.get_dummies(X[self.column]).reindex(columns=self.unique_values, fill_value=0)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/art/miniconda3/envs/deepbgc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'pfam_id'
ERROR   05/03 16:08:55   ================================================================================
ERROR   05/03 16:08:55   DeepBGC failed with KeyError: pfam_id
ERROR   05/03 16:08:55   ================================================================================

```

**Comment by prihoda** [comment]
My bad, forgot to merge the changes before releasing 😄 Please try `pip install deepbgc==0.1.25`.

**Comment by artur-matysik** [comment]
HAHAHA!
Ok, now working fine! 
Thanks for the quick fix :)

**Comment by susheelbhanu** [comment]
Hi,

I'm running version `0.1.26` and still getting this error. Any ideas how to fix it?

Thank you!

**Comment by susheelbhanu** [comment]
This issue is fixed in version `0.1.30`
